const axios = require('axios');
const store = require('../../models/store'); // Access store for project details if needed
const { getReactPipeline, getNodePipeline } = require('../../templates/pipelineTemplates');

/**
 * Resolves the Jenkins Base URL dynamicly
 */
const getBaseUrl = async () => {
  const config = await store.getConfig();
  return config.jenkinsUrl || process.env.JENKINS_URL;
};
const getAuthHeader = () => {
  const user = process.env.JENKINS_USER;
  const token = process.env.JENKINS_TOKEN;

  if (!user || !token) {
    console.error('[JenkinsExecutor] Missing credentials! Check .env (JENKINS_USER, JENKINS_TOKEN)');
    return {};
  }
  return {
    Authorization: `Basic ${Buffer.from(`${user}:${token}`).toString('base64')}`,
  };
};

/**
 * Fetches Jenkins crumb for CSRF protection
 */
const getCrumb = async () => {
  try {
    const response = await axios.get(`${await getBaseUrl()}/crumbIssuer/api/json`, {
      headers: getAuthHeader(),
    });
    return {
      [response.data.crumbRequestField]: response.data.crumb
    };
  } catch (error) {
    // console.warn('CSRF protection may not be enabled');
    return {};
  }
};

/**
 * Triggers a build for a specific job.
 */
const triggerBuild = async (jobName, params = {}) => {
  const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
  const endpoint = Object.keys(params).length > 0 ? 'buildWithParameters' : 'build';
  const crumb = await getCrumb();

  try {
    let url = `${await getBaseUrl()}/job/${encodedJobName}/${endpoint}`;
    if (endpoint === 'buildWithParameters') {
      const queryParams = new URLSearchParams(params).toString();
      url += `?${queryParams}`;
    }

    // console.log(`Triggering Jenkins build: ${url}`);

    await axios.post(url, null, {
      headers: { ...getAuthHeader(), ...crumb }
    });

    return { success: true, status: 201 };
  } catch (error) {
    if (error.response && error.response.status === 400 && endpoint === 'buildWithParameters') {
      // Just return success - the build will be queued even if params aren't discovered yet
      return { success: true, status: 201 };
    }
    throw new Error(`Jenkins Build Trigger Failed: ${error.message}`);
  }
};

/**
 * Gets logs for a build
 */
const getBuildLogs = async (jobName, buildId) => {
  try {
    const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
    const url = `${await getBaseUrl()}/job/${encodedJobName}/${buildId}/consoleText`;
    const response = await axios.get(url, { headers: getAuthHeader() });
    return response.data;
  } catch (error) {
    throw new Error(`Fetch Logs Failed: ${error.message}`);
  }
};

/**
 * Gets details of a specific build to check status
 */
const getBuildDetails = async (jobName, buildId) => {
  if (!jobName || typeof jobName !== 'string') {
    throw new Error(`Invalid Job Name: Expected string, got ${typeof jobName}`);
  }
  try {
    const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
    const url = `${await getBaseUrl()}/job/${encodedJobName}/${buildId}/api/json`;
    const response = await axios.get(url, { headers: getAuthHeader() });
    return response.data;
  } catch (error) {
    throw new Error(`Fetch Build Details Failed: ${error.message}`);
  }
};

/**
 * Checks if a job exists
 */
const checkJobExists = async (jobName) => {
  if (!jobName || typeof jobName !== 'string') {
    throw new Error(`Invalid Job Name during checkJobExists: Expected string, got ${typeof jobName}. This usually means the project is missing a 'jenkinsJob' field in the database.`);
  }
  try {
    const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
    const url = `${await getBaseUrl()}/job/${encodedJobName}/api/json`;
    await axios.get(url, { headers: getAuthHeader() });
    return true;
  } catch (error) {
    if (error.response && error.response.status === 404) return false;
    throw error;
  }
};

/**
 * Generates XML config for Jenkins job
 */
const generateConfigXml = (gitUrl, projectType, hasTests = false) => {
  // We update the pipeline template generation to include tests if hasTests is true, 
  // although currently templates have test logic built-in via 'npm test' in stage.
  // For now, we rely on the updated templates in pipelineTemplates.js 
  // which will be updated to include 'npm test'.
  const pipelineScript = projectType === 'REACT'
    ? getReactPipeline(gitUrl)
    : getNodePipeline(gitUrl);

  const escapedScript = pipelineScript
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  return `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>Auto-generated by CiGenie for ${gitUrl}</description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions>
        <hudson.model.StringParameterDefinition>
          <name>GIT_REPO</name>
          <defaultValue>${gitUrl}</defaultValue>
          <trim>false</trim>
        </hudson.model.StringParameterDefinition>
        <hudson.model.StringParameterDefinition>
          <name>BRANCH</name>
          <defaultValue>main</defaultValue>
          <trim>false</trim>
        </hudson.model.StringParameterDefinition>
        <hudson.model.StringParameterDefinition>
          <name>ACTION</name>
          <defaultValue>deploy</defaultValue>
          <trim>false</trim>
        </hudson.model.StringParameterDefinition>
        <hudson.model.StringParameterDefinition>
          <name>ENV</name>
          <defaultValue>dev</defaultValue>
          <trim>false</trim>
        </hudson.model.StringParameterDefinition>
        <hudson.model.StringParameterDefinition>
          <name>OUTPUT_PATH</name>
          <defaultValue>/var/www/html</defaultValue>
          <trim>false</trim>
        </hudson.model.StringParameterDefinition>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps">
    <script>${escapedScript}</script>
    <sandbox>true</sandbox>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>`;
};

/**
 * Creates a job
 */
const createJob = async (jobName, gitUrl, projectType = 'NODE') => {
  try {
    const crumb = await getCrumb();
    const headers = { ...getAuthHeader(), ...crumb, 'Content-Type': 'application/xml' };
    const configXml = generateConfigXml(gitUrl, projectType);
    const actualJobName = jobName.includes('/') ? jobName.split('/').pop() : jobName;
    const url = `${await getBaseUrl()}/createItem?name=${encodeURIComponent(actualJobName)}`;
    await axios.post(url, configXml, { headers });
    return true;
  } catch (error) {
    throw new Error(`Job Creation Failed: ${error.message}`);
  }
};

/**
 * Updates a job
 */
const updateJob = async (jobName, gitUrl, projectType = 'NODE') => {
  try {
    const crumb = await getCrumb();
    const headers = { ...getAuthHeader(), ...crumb, 'Content-Type': 'application/xml' };
    const configXml = generateConfigXml(gitUrl, projectType);
    const actualJobName = jobName.includes('/') ? jobName.split('/').pop() : jobName;
    const url = `${await getBaseUrl()}/job/${encodeURIComponent(actualJobName)}/config.xml`;
    await axios.post(url, configXml, { headers });
    return true;
  } catch (error) {
    throw new Error(`Job Update Failed: ${error.message}`);
  }
};

const deleteJob = async (jobName) => {
  try {
    const crumb = await getCrumb();
    const headers = { ...getAuthHeader(), ...crumb };
    const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
    const url = `${await getBaseUrl()}/job/${encodedJobName}/doDelete`;
    
    console.log(`[JenkinsExecutor] Attempting to delete job: ${jobName} at ${url}`);
    
    // Jenkins doDelete returns a 302 on success. Axios follows it by default.
    // We use a POST request as required by Jenkins.
    await axios.post(url, null, { 
      headers,
      maxRedirects: 5,
      validateStatus: (status) => status >= 200 && status < 400 // Accept 302
    });
    
    console.log(`[JenkinsExecutor] Delete request initiated for ${jobName}`);
    return true;
  } catch (error) {
    // If it's a 404, the job might already be gone, which we can treat as success for deletion
    if (error.response && error.response.status === 404) {
      console.log(`[JenkinsExecutor] Job ${jobName} already deleted or not found.`);
      return true;
    }
    
    console.error(`[JenkinsExecutor] Job Deletion Failed: ${error.message}`);
    throw new Error(`Job Deletion Failed: ${error.message}`);
  }
};

/**
 * Gets details of a specific job (including last build info).
 * @param {string} jobName 
 */
const getJobDetails = async (jobName) => {
  const encodedJobName = jobName.split('/').map(encodeURIComponent).join('/job/');
  try {
    const url = `${await getBaseUrl()}/job/${encodedJobName}/api/json`;

    const response = await axios.get(url, { headers: getAuthHeader() });
    return response.data;
  } catch (error) {
    throw new Error(`Fetch Job Details Failed: ${error.message}`);
  }
};

/**
 * Parses generic terminal output to extract test results.
 */
const parseTestResults = (logs) => {
  if (!logs) return null;

  const results = {
    passed: 0,
    failed: 0,
    total: 0,
    snapshots: 0,
    snapshotTotal: 0
  };

  // 1. Try Jest Match (Specific)
  const jestTestMatch = logs.match(/Tests:\s+(?:(\d+)\s+failed,\s+)?(?:(\d+)\s+passed,\s+)?(?:(\d+)\s+total)/);
  if (jestTestMatch) {
    results.failed = parseInt(jestTestMatch[1] || '0');
    results.passed = parseInt(jestTestMatch[2] || '0');
    results.total = parseInt(jestTestMatch[3] || '0');

    const snapshotMatch = logs.match(/Snapshots:\s+(?:(\d+)\s+passed,\s+)?(?:(\d+)\s+total)/);
    if (snapshotMatch) {
      results.snapshots = parseInt(snapshotMatch[1] || '0');
      results.snapshotTotal = parseInt(snapshotMatch[2] || '0');
    }
  } else {
    // 2. Try Generic "X passed, Y failed"
    const genericMatch = logs.match(/(\d+)\s+passed.*?(?:(\d+)\s+failed|(\d+)\s+failures)/i);
    if (genericMatch) {
      results.passed = parseInt(genericMatch[1]);
      results.failed = parseInt(genericMatch[2] || genericMatch[3] || '0');
      results.total = results.passed + results.failed;
    } else {
      // 3. Fallback to simple counts
      const passedCount = logs.match(/(\d+)\s+(?:passed|✔)/i);
      const failedCount = logs.match(/(\d+)\s+(?:failed|failures|✖)/i);
      if (passedCount) results.passed = parseInt(passedCount[1]);
      if (failedCount) results.failed = parseInt(failedCount[1]);
      results.total = results.passed + results.failed;
    }
  }

  return results.total > 0 ? results : null;
};

/**
 * Fetches build history for all jobs in Jenkins.
 * Returns array of build objects with normalized format.
 */
const getAllBuildsHistory = async () => {
  try {
    const url = `${await getBaseUrl()}/api/json?tree=jobs[name,builds[number,result,timestamp,duration,url,actions[parameters[name,value]]]]`;
    const response = await axios.get(url, { headers: getAuthHeader() });
    const jobs = response.data.jobs || [];

    const allBuilds = [];

    for (const job of jobs) {
      const builds = job.builds || [];
      for (const build of builds) {
        const paramsAction = (build.actions || []).find(a => a && a.parameters);
        const params = {};
        if (paramsAction) {
          paramsAction.parameters.forEach(p => {
            params[p.name] = p.value;
          });
        }

        const buildObj = {
          id: `jenkins_${job.name}_${build.number}`,
          projectId: job.name,
          buildNumber: build.number,
          status: build.result === 'SUCCESS' ? 'SUCCESS' : build.result === 'FAILURE' ? 'FAILED' : build.result || 'IN_PROGRESS',
          startTime: new Date(build.timestamp),
          endTime: build.duration > 0 ? new Date(build.timestamp + build.duration) : null,
          duration: build.duration,
          url: build.url,
          params: params
        };

        // If it's a test action, try to fetch logs and parse results
        if (params.ACTION === 'test' && build.result) {
          try {
            const logs = await getBuildLogs(job.name, build.number);
            buildObj.testSummary = parseTestResults(logs);
          } catch (e) {
            console.warn(`Failed to parse test logs for ${job.name}#${build.number}`);
          }
        }

        allBuilds.push(buildObj);
      }
    }

    return allBuilds;
  } catch (error) {
    console.error('Failed to fetch Jenkins build history:', error.message);
    return [];
  }
};

/**
 * Checks connectivity to Jenkins master
 */
const getJenkinsStatus = async () => {
  try {
    const url = `${await getBaseUrl()}/api/json?tree=numExecutors`;
    await axios.get(url, { headers: getAuthHeader(), timeout: 3000 });
    return 'Optimal';
  } catch (error) {
    console.warn('[JenkinsExecutor] Status Check Failed:', error.message);
    return 'Disconnected';
  }
};

const getFileSystemPaths = async () => {
  try {
    // Groovy script to list directories recursively up to depth 5 across all roots
    const script = `
      def paths = []
      def roots = File.listRoots().collect { it.absolutePath }
      
      def findDirs
      findDirs = { File dir, int depth ->
          if (depth > 5 || paths.size() >= 200) return
          try {
              if (dir.exists() && dir.isDirectory()) {
                  paths.add(dir.absolutePath)
                  dir.listFiles()?.each { child ->
                      if (child.isDirectory() && !child.name.startsWith(".") && !["Windows", "Program Files", "Program Files (x86)", "node_modules", "AppData"].contains(child.name)) {
                          findDirs(child, depth + 1)
                      }
                  }
              }
          } catch (e) {}
      }
      
      roots.each { r -> findDirs(new File(r), 0) }
      println paths.unique().join("\\n")
    `;

    const url = `${await getBaseUrl()}/scriptText`;
    const params = new URLSearchParams();
    params.set('script', script);

    const response = await axios.post(url, params.toString(), {
      headers: {
        ...getAuthHeader(),
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    });

    return response.data.split('\n').filter(p => p.trim() !== '');
  } catch (error) {
    console.warn('[JenkinsExecutor] Failed to fetch live paths:', error.message);
    return []; // Fallback to empty if script console is disabled or failed
  }
};

module.exports = {
  triggerBuild,
  getBuildLogs,
  getBuildDetails,
  checkJobExists,
  createJob,
  updateJob,
  deleteJob,
  getJobDetails,
  getAllBuildsHistory,
  getJenkinsStatus,
  getFileSystemPaths
};
